"""
``plimsoll init`` — Interactive 3-question wizard that generates ``plimsoll.toml``.

The generated file is human-readable TOML consumed by both the Python SDK
(``PlimsollConfig``) and the Rust RPC Proxy (via env-var expansion in
``docker-compose.yml``).
"""

from __future__ import annotations

import os
from typing import Dict


# ── Chain → default upstream RPC ──────────────────────────────────

_RPC_DEFAULTS: Dict[str, str] = {
    "ethereum":  "https://eth-mainnet.g.alchemy.com/v2/YOUR_KEY",
    "polygon":   "https://polygon-mainnet.g.alchemy.com/v2/YOUR_KEY",
    "arbitrum":  "https://arb-mainnet.g.alchemy.com/v2/YOUR_KEY",
    "base":      "https://base-mainnet.g.alchemy.com/v2/YOUR_KEY",
    "solana":    "https://api.mainnet-beta.solana.com",
}

_CHAIN_IDS: Dict[str, int] = {
    "ethereum":  1,
    "polygon":   137,
    "arbitrum":  42161,
    "base":      8453,
    "solana":    0,
}

# ── TOML template (stdlib string formatting, no Jinja) ────────────

_TEMPLATE = """\
# Plimsoll Protocol Configuration
# Generated by `plimsoll init`
# Docs: https://docs.plimsoll-protocol.dev

[plimsoll]
chain        = "{chain}"
chain_id     = {chain_id}
framework    = "{framework}"

[velocity]
# v_max is derived from max_daily_spend: {max_daily_spend} USD / 86400 s
max_daily_spend = {max_daily_spend}
v_max           = {v_max}
window_seconds  = 300.0

[entropy]
entropy_threshold      = 5.0
enable_pattern_matching = true

[proxy]
upstream_rpc = "{upstream_rpc}"
host         = "0.0.0.0"
port         = 8545
"""


def _ask(prompt: str, default: str = "") -> str:
    """Prompt the user; return *default* on empty input."""
    raw = input(prompt).strip()
    return raw if raw else default


def run_init(output_dir: str | None = None) -> str:
    """Interactive wizard that writes ``plimsoll.toml``.

    Returns the absolute path of the generated file (useful for testing).
    """
    print("\n  \033[1mPlimsoll Protocol \u2014 Configuration Wizard\033[0m\n")

    # Q1 — Chain
    chain = _ask(
        "  1. Which chain?  [ethereum/polygon/arbitrum/base/solana]: ",
        default="ethereum",
    ).lower()
    if chain not in _RPC_DEFAULTS:
        print(f"  \u26a0  Unknown chain '{chain}', defaulting to ethereum")
        chain = "ethereum"

    # Q2 — Budget
    budget_raw = _ask("  2. Max daily agent spend (USD)?  [1000]: ", default="1000")
    try:
        max_daily_spend = float(budget_raw)
    except ValueError:
        print(f"  \u26a0  Invalid number '{budget_raw}', defaulting to 1000")
        max_daily_spend = 1000.0

    # Q3 — Framework
    framework = _ask(
        "  3. Agent framework?  [langchain/openclaw/automaton/eliza/custom]: ",
        default="custom",
    ).lower()

    # Derived values
    v_max = max_daily_spend / 86400.0
    upstream_rpc = _RPC_DEFAULTS[chain]
    chain_id = _CHAIN_IDS[chain]

    content = _TEMPLATE.format(
        chain=chain,
        chain_id=chain_id,
        framework=framework,
        max_daily_spend=max_daily_spend,
        v_max=round(v_max, 8),
        upstream_rpc=upstream_rpc,
    )

    base = output_dir or os.getcwd()
    output_path = os.path.join(base, "plimsoll.toml")
    with open(output_path, "w") as fh:
        fh.write(content)

    print(f"\n  \u2705  Written to {output_path}")
    print("  Next: run \033[1mplimsoll up\033[0m to start the RPC proxy\n")
    return output_path
